version: 2.1
orbs:
    node: circleci/node@5.0.1
jobs:
    test:
        executor:
            name: node/default
            tag: '16.13'
        steps:
            - checkout
            - run: npm install
            - run:
                # Why only production? See: https://overreacted.io/npm-audit-broken-by-design/#what-next
                name: audit
                command: npm audit --production
            - run: npm run lint
            - run: echo "npm run test"

workflows:
    version: '2.1'
    test_lint:
        jobs:
            - test
