name: codecov

on:
  push:
    branches: [ "staging", "master" ]
  pull_request:
    branches: [ "staging", "master" ]

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3.1.1
      with:
        verbose: true
        fail_ci_if_error: true

